In [1]:
import os
from glob import glob
import pandas as pd
from functools import reduce
from xml.etree import ElementTree as et

In [6]:
#load xml files
xml_list = glob('./*.xml')
xml_list = list(map(lambda x: x.replace('\\','/'),xml_list))

In [7]:
xml_list

['./00236.xml',
 './00249.xml',
 './00386.xml',
 './00136.xml',
 './00145.xml',
 './00215.xml',
 './00490.xml',
 './00223.xml',
 './00289.xml',
 './00017.xml',
 './00400.xml',
 './00134.xml',
 './00451.xml',
 './00328.xml',
 './00397.xml',
 './00094.xml',
 './00443.xml',
 './00433.xml',
 './00206.xml',
 './00452.xml',
 './00533.xml',
 './00272.xml',
 './00118.xml',
 './00210.xml',
 './00174.xml',
 './00155.xml',
 './00405.xml',
 './00237.xml',
 './00133.xml',
 './00166.xml',
 './00564.xml',
 './00412.xml',
 './00407.xml',
 './00280.xml',
 './00234.xml',
 './00323.xml',
 './00169.xml',
 './00358.xml',
 './00086.xml',
 './00028.xml',
 './00442.xml',
 './00187.xml',
 './00090.xml',
 './00362.xml',
 './00253.xml',
 './00322.xml',
 './00113.xml',
 './00359.xml',
 './00345.xml',
 './00262.xml',
 './00461.xml',
 './00325.xml',
 './00163.xml',
 './00221.xml',
 './00366.xml',
 './00536.xml',
 './00509.xml',
 './00472.xml',
 './00432.xml',
 './00268.xml',
 './00127.xml',
 './00422.xml',
 './00002.xml',
 './00363.xml',
 './00152.xml',
 './00077.xml',
 './00380.xml',
 './00172.xml',
 './00200.xml',
 './00494.xml',
 './00203.xml',
 './00269.xml',
 './00394.xml',
 './00320.xml',
 './00427.xml',
 './00491.xml',
 './00246.xml',
 './00106.xml',
 './00361.xml',
 './00263.xml',
 './00450.xml',
 './00225.xml',
 './00270.xml',
 './00455.xml',
 './00027.xml',
 './00327.xml',
 './00292.xml',
 './00148.xml',
 './00350.xml',
 './00149.xml',
 './00290.xml',
 './00403.xml',
 './00224.xml',
 './0436.xml',
 './00004.xml',
 './00119.xml',
 './00467.xml',
 './00254.xml',
 './00255.xml',
 './00139.xml',
 './00179.xml',
 './00332.xml',
 './00413.xml',
 './00445.xml',
 './00498.xml',
 './00438.xml',
 './00480.xml',
 './00284.xml',
 './00302.xml',
 './00465.xml',
 './00202.xml',
 './00395.xml',
 './00572.xml',
 './00078.xml',
 './00291.xml',
 './00365.xml',
 './00535.xml',
 './00463.xml',
 './00369.xml',
 './00040.xml',
 './00157.xml',
 './00402.xml',
 './00101.xml',
 './00241.xml',
 './00453.xml',
 './00033.xml',
 './00256.xml',
 './00277.xml',
 './00100.xml',
 './00274.xml',
 './00186.xml',
 './00084.xml',
 './00297.xml',
 './00309.xml',
 './00183.xml',
 './00107.xml',
 './00551.xml',
 './00300.xml',
 './00475.xml',
 './00138.xml',
 './00481.xml',
 './00087.xml',
 './00483.xml',
 './00238.xml',
 './00069.xml',
 './00340.xml',
 './00140.xml',
 './00574.xml',
 './00408.xml',
 './00233.xml',
 './00499.xml',
 './00191.xml',
 './00244.xml',
 './00368.xml',
 './00111.xml',
 './00308.xml',
 './00089.xml',
 './00023.xml',
 './00351.xml',
 './00287.xml',
 './00285.xml',
 './00232.xml',
 './00301.xml',
 './00123.xml',
 './00414.xml',
 './00147.xml',
 './00250.xml',
 './00537.xml',
 './00258.xml',
 './00334.xml',
 './00431.xml',
 './00074.xml',
 './00459.xml',
 './00235.xml',
 './00391.xml',
 './00209.xml',
 './00020.xml',
 './00049.xml',
 './00486.xml',
 './00014.xml',
 './00058.xml',
 './00182.xml',
 './00388.xml',
 './00360.xml',
 './00418.xml',
 './00146.xml',
 './00142.xml',
 './00156.xml',
 './00356.xml',
 './00398.xml',
 './00011.xml',
 './00278.xml',
 './00245.xml',
 './00259.xml',
 './00538.xml',
 './00343.xml',
 './00131.xml',
 './00466.xml',
 './00192.xml',
 './00457.xml',
 './00097.xml',
 './00243.xml',
 './00048.xml',
 './00080.xml',
 './00546.xml',
 './00248.xml',
 './00529.xml',
 './00282.xml',
 './00162.xml',
 './00030.xml',
 './00392.xml',
 './00409.xml',
 './00283.xml',
 './00046.xml',
 './00364.xml',
 './00204.xml',
 './00313.xml',
 './00428.xml',
 './00489.xml',
 './00114.xml',
 './00347.xml',
 './00261.xml',
 './00105.xml',
 './00381.xml',
 './00053.xml',
 './00072.xml',
 './00319.xml',
 './00082.xml',
 './00083.xml',
 './00524.xml',
 './00419.xml',
 './00421.xml',
 './00066.xml',
 './00399.xml',
 './00154.xml',
 './00211.xml',
 './00449.xml',
 './00226.xml',
 './00469.xml',
 './00024.xml',
 './00429.xml',
 './00384.xml',
 './00063.xml',
 './00042.xml',
 './00167.xml',
 './00205.xml',
 './00054.xml',
 './00007.xml',
 './00016.xml',
 './00129.xml',
 './00055.xml',
 './00216.xml',
 './00273.xml',
 './00121.xml',
 './00344.xml',
 './00390.xml',
 './00374.xml',
 './00201.xml',
 './00076.xml',
 './00251.xml',
 './00008.xml',
 './00112.xml',
 './00375.xml',
 './00021.xml',
 './00295.xml',
 './00312.xml',
 './00468.xml',
 './00296.xml',
 './00337.xml',
 './00462.xml',
 './00032.xml',
 './00110.xml',
 './00045.xml',
 './00229.xml',
 './00417.xml',
 './00305.xml',
 './00434.xml',
 './00025.xml',
 './00471.xml',
 './00093.xml',
 './00420.xml',
 './00158.xml',
 './00220.xml',
 './00487.xml',
 './00143.xml',
 './00012.xml',
 './00099.xml',
 './00181.xml',
 './00430.xml',
 './00116.xml',
 './00098.xml',
 './00213.xml',
 './00003.xml',
 './00304.xml',
 './00352.xml',
 './00153.xml',
 './00052.xml',
 './00435.xml',
 './00022.xml',
 './00585.xml',
 './00005.xml',
 './00001.xml',
 './00496.xml',
 './00488.xml',
 './00013.xml',
 './00160.xml',
 './00173.xml',
 './00222.xml',
 './00348.xml',
 './00317.xml',
 './00437.xml',
 './00349.xml',
 './00299.xml',
 './00355.xml',
 './00037.xml',
 './00410.xml',
 './00474.xml',
 './00193.xml',
 './00034.xml',
 './00060.xml',
 './00279.xml',
 './00389.xml',
 './00207.xml',
 './00195.xml',
 './00095.xml',
 './00260.xml',
 './00506.xml',
 './00006.xml',
 './00331.xml',
 './00411.xml',
 './00396.xml',
 './00335.xml',
 './00326.xml',
 './00306.xml',
 './00218.xml',
 './00534.xml',
 './00460.xml',
 './00102.xml',
 './00070.xml',
 './00545.xml',
 './00318.xml',
 './00338.xml',
 './00010.xml',
 './00377.xml',
 './00569.xml',
 './00075.xml',
 './00184.xml',
 './00198.xml',
 './00497.xml',
 './00316.xml',
 './00444.xml',
 './00039.xml',
 './00354.xml',
 './00050.xml',
 './00508.xml',
 './00476.xml',
 './00044.xml',
 './00329.xml',
 './00321.xml',
 './00473.xml',
 './00096.xml',
 './00141.xml',
 './00298.xml',
 './00584.xml',
 './00247.xml',
 './00240.xml',
 './00426.xml',
 './00124.xml',
 './00314.xml',
 './00150.xml',
 './00159.xml',
 './00370.xml',
 './00307.xml',
 './00231.xml',
 './00376.xml',
 './00341.xml',
 './00031.xml',
 './00104.xml',
 './00294.xml',
 './00178.xml',
 './00081.xml',
 './00464.xml',
 './00071.xml',
 './00371.xml',
 './00059.xml',
 './00367.xml',
 './00176.xml',
 './00271.xml',
 './00416.xml',
 './00286.xml',
 './00190.xml',
 './00056.xml',
 './00493.xml',
 './00454.xml',
 './00135.xml',
 './00061.xml',
 './00441.xml',
 './00041.xml',
 './00382.xml',
 './00580.xml',
 './00214.xml',
 './00387.xml',
 './00446.xml',
 './00458.xml',
 './00275.xml',
 './00065.xml',
 './00144.xml',
 './00165.xml',
 './00315.xml',
 './00064.xml',
 './00532.xml',
 './00267.xml',
 './00073.xml',
 './00385.xml',
 './00311.xml',
 './00171.xml',
 './00117.xml',
 './00018.xml',
 './00281.xml',
 './00185.xml',
 './00057.xml',
 './00103.xml',
 './00197.xml',
 './00276.xml',
 './00492.xml',
 './00500.xml',
 './00266.xml',
 './00565.xml',
 './00378.xml',
 './00092.xml',
 './00043.xml',
 './00051.xml',
 './00009.xml',
 './00170.xml',
 './00485.xml',
 './00015.xml',
 './00177.xml',
 './00108.xml',
 './00085.xml',
 './00227.xml',
 './00372.xml',
 './00079.xml',
 './00393.xml',
 './00252.xml',
 './00599.xml',
 './00415.xml',
 './00125.xml',
 './00194.xml',
 './00115.xml',
 './00130.xml',
 './00333.xml',
 './00230.xml',
 './00482.xml',
 './00339.xml',
 './00208.xml',
 './00091.xml',
 './00439.xml',
 './00303.xml',
 './00212.xml',
 './00062.xml',
 './00373.xml',
 './00228.xml',
 './00219.xml',
 './00164.xml',
 './00423.xml',
 './00035.xml',
 './00425.xml',
 './00479.xml',
 './00257.xml',
 './00440.xml',
 './00036.xml',
 './00456.xml',
 './00132.xml',
 './00478.xml',
 './00404.xml',
 './00288.xml',
 './00470.xml',
 './00109.xml',
 './00239.xml',
 './00406.xml',
 './00128.xml',
 './00199.xml',
 './00424.xml',
 './00265.xml',
 './00264.xml',
 './00047.xml',
 './00477.xml',
 './00353.xml',
 './00401.xml',
 './00038.xml',
 './00448.xml',
 './00336.xml',
 './00346.xml',
 './00447.xml',
 './00019.xml',
 './00242.xml',
 './00510.xml',
 './00293.xml',
 './00126.xml',
 './00088.xml',
 './00151.xml',
 './00379.xml',
 './00068.xml',
 './00324.xml',
 './00484.xml',
 './00026.xml',
 './00330.xml',
 './00188.xml',
 './00383.xml',
 './00556.xml',
 './00175.xml',
 './00566.xml',
 './00122.xml',
 './00357.xml',
 './00342.xml',
 './00029.xml',
 './00196.xml',
 './00067.xml',
 './00217.xml',
 './00495.xml',
 './00120.xml']

In [8]:
# read xml files and extract filename, size(width,height), object(name,xmin,xmax,ymin,ymax)

def extract_text(filename):
    tree = et.parse(filename)
    root = tree.getroot()
    image_name = root.find('filename').text
    width = root.find('size').find('width').text
    height = root.find('size').find('height').text

    objs = root.findall('object')
    parser = []
    for obj in objs:
        name = obj.find('name').text
        bndbox = obj.find('bndbox')
        xmin = bndbox.find('xmin').text
        xmax = bndbox.find('xmax').text
        ymin = bndbox.find('ymin').text
        ymax = bndbox.find('ymax').text
        parser.append([image_name, width, height, name, xmin, xmax, ymin, ymax])

    return parser

parser_all = list(map(extract_text,xml_list))
data = reduce(lambda x,y: x+y, parser_all)

In [9]:
df = pd.DataFrame(data,columns = ['filename','width','height','name','xmin','xmax','ymin','ymax'])
df.head()

    filename width height name xmin  xmax ymin ymax
0  00236.jpg   600    450  car   20   573  137  421
1  00249.jpg  1280    853  car  630  1221  317  579
2  00386.jpg  1280   1024  car   67  1230  320  826
3  00136.jpg  1280    853  car  304   379  658  700
4  00136.jpg  1280    853  car  975  1185  654  738

In [10]:
df.shape

(815, 8)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  815 non-null    object
 1   width     815 non-null    object
 2   height    815 non-null    object
 3   name      815 non-null    object
 4   xmin      815 non-null    object
 5   xmax      815 non-null    object
 6   ymin      815 non-null    object
 7   ymax      815 non-null    object
dtypes: object(8)
memory usage: 51.1+ KB

In [12]:
# type conversion
cols = ['width', 'height', 'xmin', 'xmax', 'ymin', 'ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  815 non-null    object
 1   width     815 non-null    int64
 2   height    815 non-null    int64
 3   name      815 non-null    object
 4   xmin      815 non-null    int64
 5   xmax      815 non-null    int64
 6   ymin      815 non-null    int64
 7   ymax      815 non-null    int64
dtypes: int64(6), object(2)
memory usage: 51.1+ KB

In [13]:
# center x and center y
df['center_x'] = ((df['xmax'] + df['xmin'])/2)/df['width']
df['center_y'] = ((df['ymax'] + df['ymin'])/2)/df['height']

# w: width of the bounding box
df['w'] = (df['xmax'] - df['xmin'])/df['width']

# h" height of the bounding box
df['h'] = (df['ymax'] - df['ymin'])/df['height']

In [14]:
df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,00236.jpg,600,450,car,20,573,137,421,0.494167,0.620000,0.921667,0.631111
1,00249.jpg,1280,853,car,630,1221,317,579,0.723047,0.525205,0.461719,0.307151
2,00386.jpg,1280,1024,car,67,1230,320,826,0.506641,0.559570,0.908594,0.494141
3,00136.jpg,1280,853,car,304,379,658,700,0.266797,0.796014,0.058594,0.049238
4,00136.jpg,1280,853,car,975,1185,654,738,0.843750,0.815944,0.164062,0.098476

In [17]:
# 80% of images for training the model
images = df['filename'].unique()
img_df = pd.DataFrame(images,columns=['filename'])
img_train = tuple(img_df.sample(frac=0.8, random_state=42)['filename'])
img_test = tuple(img_df[~img_df['filename'].isin(img_train)]['filename'])
img_train

('00188.jpg',
 '0436.jpg',
 '00490.jpg',
 '00205.jpg',
 '00290.jpg',
 '00534.jpg',
 '00459.jpg',
 '00260.jpg',
 '00213.jpg',
 '00265.jpg',
 '00111.jpg',
 '00388.jpg',
 '00068.jpg',
 '00556.jpg',
 '00400.jpg',
 '00423.jpg',
 '00104.jpg',
 '00564.jpg',
 '00392.jpg',
 '00390.jpg',
 '00537.jpg',
 '00027.jpg',
 '00481.jpg',
 '00408.jpg',
 '00154.jpg',
 '00045.jpg',
 '00263.jpg',
 '00176.jpg',
 '00458.jpg',
 '00469.jpg',
 '00266.jpg',
 '00235.jpg',
 '00218.jpg',
 '00017.jpg',
 '00088.jpg',
 '00200.jpg',
 '00343.jpg',
 '00084.jpg',
 '00135.jpg',
 '00146.jpg',
 '00332.jpg',
 '00297.jpg',
 '00536.jpg',
 '00196.jpg',
 '00599.jpg',
 '00162.jpg',
 '00098.jpg',
 '00149.jpg',
 '00379.jpg',
 '00329.jpg',
 '00453.jpg',
 '00463.jpg',
 '00246.jpg',
 '00082.jpg',
 '00524.jpg',
 '00416.jpg',
 '00300.jpg',
 '00320.jpg',
 '00386.jpg',
 '00106.jpg',
 '00231.jpg',
 '00411.jpg',
 '00378.jpg',
 '00022.jpg',
 '00363.jpg',
 '00020.jpg',
 '00498.jpg',
 '00203.jpg',
 '00439.jpg',
 '00280.jpg',
 '00394.jpg',
 '00361.jpg',
 '00236.jpg',
 '00134.jpg',
 '00167.jpg',
 '00118.jpg',
 '00315.jpg',
 '00373.jpg',
 '00495.jpg',
 '00270.jpg',
 '00447.jpg',
 '00198.jpg',
 '00206.jpg',
 '00058.jpg',
 '00083.jpg',
 '00116.jpg',
 '00120.jpg',
 '00028.jpg',
 '00456.jpg',
 '00113.jpg',
 '00406.jpg',
 '00409.jpg',
 '00311.jpg',
 '00242.jpg',
 '00181.jpg',
 '00055.jpg',
 '00448.jpg',
 '00326.jpg',
 '00347.jpg',
 '00389.jpg',
 '00494.jpg',
 '00132.jpg',
 '00013.jpg',
 '00099.jpg',
 '00158.jpg',
 '00067.jpg',
 '00049.jpg',
 '00009.jpg',
 '00306.jpg',
 '00073.jpg',
 '00471.jpg',
 '00368.jpg',
 '00197.jpg',
 '00489.jpg',
 '00044.jpg',
 '00342.jpg',
 '00199.jpg',
 '00460.jpg',
 '00025.jpg',
 '00230.jpg',
 '00096.jpg',
 '00292.jpg',
 '00245.jpg',
 '00491.jpg',
 '00175.jpg',
 '00094.jpg',
 '00105.jpg',
 '00308.jpg',
 '00418.jpg',
 '00446.jpg',
 '00452.jpg',
 '00051.jpg',
 '00509.jpg',
 '00121.jpg',
 '00382.jpg',
 '00079.jpg',
 '00351.jpg',
 '00155.jpg',
 '00375.jpg',
 '00090.jpg',
 '00474.jpg',
 '00324.jpg',
 '00184.jpg',
 '00190.jpg',
 '00256.jpg',
 '00070.jpg',
 '00412.jpg',
 '00078.jpg',
 '00281.jpg',
 '00072.jpg',
 '00065.jpg',
 '00472.jpg',
 '00383.jpg',
 '00174.jpg',
 '00433.jpg',
 '00007.jpg',
 '00380.jpg',
 '00421.jpg',
 '00159.jpg',
 '00004.jpg',
 '00030.jpg',
 '00293.jpg',
 '00210.jpg',
 '00207.jpg',
 '00110.jpg',
 '00500.jpg',
 '00215.jpg',
 '00535.jpg',
 '00322.jpg',
 '00095.jpg',
 '00443.jpg',
 '00047.jpg',
 '00370.jpg',
 '00136.jpg',
 '00303.jpg',
 '00080.jpg',
 '00127.jpg',
 '00202.jpg',
 '00566.jpg',
 '00219.jpg',
 '00166.jpg',
 '00546.jpg',
 '00420.jpg',
 '00405.jpg',
 '00223.jpg',
 '00182.jpg',
 '00478.jpg',
 '00302.jpg',
 '00358.jpg',
 '00023.jpg',
 '00038.jpg',
 '00369.jpg',
 '00291.jpg',
 '00276.jpg',
 '00209.jpg',
 '00141.jpg',
 '00115.jpg',
 '00069.jpg',
 '00538.jpg',
 '00059.jpg',
 '00441.jpg',
 '00071.jpg',
 '00226.jpg',
 '00050.jpg',
 '00035.jpg',
 '00087.jpg',
 '00081.jpg',
 '00172.jpg',
 '00299.jpg',
 '00258.jpg',
 '00356.jpg',
 '00305.jpg',
 '00493.jpg',
 '00353.jpg',
 '00259.jpg',
 '00225.jpg',
 '00465.jpg',
 '00194.jpg',
 '00340.jpg',
 '00224.jpg',
 '00244.jpg',
 '00482.jpg',
 '00532.jpg',
 '00124.jpg',
 '00455.jpg',
 '00445.jpg',
 '00147.jpg',
 '00123.jpg',
 '00457.jpg',
 '00401.jpg',
 '00427.jpg',
 '00279.jpg',
 '00497.jpg',
 '00346.jpg',
 '00040.jpg',
 '00031.jpg',
 '00437.jpg',
 '00312.jpg',
 '00314.jpg',
 '00018.jpg',
 '00129.jpg',
 '00468.jpg',
 '00485.jpg',
 '00222.jpg',
 '00580.jpg',
 '00143.jpg',
 '00169.jpg',
 '00131.jpg',
 '00138.jpg',
 '00165.jpg',
 '00112.jpg',
 '00393.jpg',
 '00052.jpg',
 '00268.jpg',
 '00036.jpg',
 '00016.jpg',
 '00395.jpg',
 '00417.jpg',
 '00492.jpg',
 '00341.jpg',
 '00499.jpg',
 '00041.jpg',
 '00086.jpg',
 '00338.jpg',
 '00192.jpg',
 '00337.jpg',
 '00140.jpg',
 '00267.jpg',
 '00574.jpg',
 '00034.jpg',
 '00435.jpg',
 '00241.jpg',
 '00371.jpg',
 '00467.jpg',
 '00238.jpg',
 '00024.jpg',
 '00335.jpg',
 '00254.jpg',
 '00247.jpg',
 '00101.jpg',
 '00360.jpg',
 '00048.jpg',
 '00054.jpg',
 '00193.jpg',
 '00170.jpg',
 '00240.jpg',
 '00349.jpg',
 '00126.jpg',
 '00496.jpg',
 '00033.jpg',
 '00037.jpg',
 '00381.jpg',
 '00177.jpg',
 '00114.jpg',
 '00274.jpg',
 '00085.jpg',
 '00585.jpg',
 '00318.jpg',
 '00454.jpg',
 '00001.jpg',
 '00150.jpg',
 '00160.jpg',
 '00352.jpg',
 '00464.jpg',
 '00354.jpg',
 '00572.jpg',
 '00014.jpg',
 '00440.jpg',
 '00476.jpg',
 '00010.jpg',
 '00026.jpg',
 '00376.jpg',
 '00399.jpg',
 '00479.jpg',
 '00195.jpg',
 '00414.jpg',
 '00551.jpg',
 '00466.jpg',
 '00076.jpg',
 '00066.jpg',
 '00365.jpg',
 '00157.jpg',
 '00298.jpg',
 '00053.jpg',
 '00057.jpg',
 '00316.jpg',
 '00277.jpg',
 '00012.jpg',
 '00092.jpg',
 '00284.jpg',
 '00339.jpg',
 '00171.jpg',
 '00309.jpg',
 '00108.jpg',
 '00253.jpg',
 '00424.jpg',
 '00077.jpg',
 '00487.jpg',
 '00327.jpg',
 '00063.jpg',
 '00142.jpg',
 '00214.jpg',
 '00287.jpg',
 '00451.jpg',
 '00323.jpg',
 '00133.jpg',
 '00431.jpg',
 '00483.jpg',
 '00117.jpg',
 '00508.jpg',
 '00261.jpg',
 '00119.jpg',
 '00325.jpg',
 '00429.jpg',
 '00227.jpg',
 '00039.jpg',
 '00061.jpg',
 '00486.jpg',
 '00187.jpg',
 '00091.jpg',
 '00275.jpg',
 '00529.jpg',
 '00220.jpg',
 '00321.jpg',
 '00344.jpg',
 '00125.jpg',
 '00145.jpg',
 '00374.jpg',
 '00257.jpg',
 '00179.jpg',
 '00319.jpg',
 '00264.jpg',
 '00046.jpg',
 '00372.jpg',
 '00074.jpg',
 '00255.jpg',
 '00003.jpg',
 '00204.jpg',
 '00422.jpg',
 '00359.jpg',
 '00407.jpg',
 '00296.jpg',
 '00006.jpg',
 '00097.jpg',
 '00357.jpg',
 '00237.jpg',
 '00144.jpg',
 '00419.jpg',
 '00008.jpg',
 '00294.jpg',
 '00430.jpg',
 '00301.jpg',
 '00056.jpg',
 '00130.jpg',
 '00475.jpg',
 '00002.jpg',
 '00107.jpg',
 '00100.jpg',
 '00151.jpg',
 '00289.jpg',
 '00506.jpg',
 '00477.jpg',
 '00152.jpg',
 '00005.jpg',
 '00397.jpg',
 '00089.jpg',
 '00442.jpg',
 '00178.jpg',
 '00128.jpg',
 '00103.jpg',
 '00313.jpg',
 '00064.jpg',
 '00093.jpg',
 '00208.jpg',
 '00333.jpg',
 '00102.jpg',
 '00449.jpg')

In [18]:
len(img_train), len(img_test)

(417, 104)

In [19]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [20]:
train_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,00236.jpg,600,450,car,20,573,137,421,0.494167,0.620000,0.921667,0.631111
2,00386.jpg,1280,1024,car,67,1230,320,826,0.506641,0.559570,0.908594,0.494141
3,00136.jpg,1280,853,car,304,379,658,700,0.266797,0.796014,0.058594,0.049238
4,00136.jpg,1280,853,car,975,1185,654,738,0.843750,0.815944,0.164062,0.098476
5,00136.jpg,1280,853,car,620,813,663,762,0.559766,0.835287,0.150781,0.116061

In [21]:
test_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
1,00249.jpg,1280,853,car,630,1221,317,579,0.723047,0.525205,0.461719,0.307151
19,00328.jpg,1280,960,car,80,689,376,746,0.300391,0.584375,0.475781,0.385417
30,00533.jpg,500,312,car,42,483,68,261,0.525000,0.527244,0.882000,0.618590
31,00272.jpg,1280,960,car,363,534,544,617,0.350391,0.604688,0.133594,0.076042
32,00272.jpg,1280,960,car,460,640,673,751,0.429688,0.741667,0.140625,0.081250

In [22]:
# label encoding
def label_encoding(x):
    labels = {'person':0, 'car':1, 'chair':2, 'bottle':3, 'dog':4, 'bicycle':5, 'motorbike':6}
    return labels[x]

train_df['id'] = train_df['name'].apply(label_encoding)
test_df['id'] = test_df['name'].apply(label_encoding)

/tmp/ipykernel_2123/3604471879.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['id'] = train_df['name'].apply(label_encoding)
/tmp/ipykernel_2123/3604471879.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['id'] = test_df['name'].apply(label_encoding)

In [23]:
train_df.head(10)

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
0,00236.jpg,600,450,car,20,573,137,421,0.494167,0.620000,0.921667,0.631111,1
2,00386.jpg,1280,1024,car,67,1230,320,826,0.506641,0.559570,0.908594,0.494141,1
3,00136.jpg,1280,853,car,304,379,658,700,0.266797,0.796014,0.058594,0.049238,1
4,00136.jpg,1280,853,car,975,1185,654,738,0.843750,0.815944,0.164062,0.098476,1
5,00136.jpg,1280,853,car,620,813,663,762,0.559766,0.835287,0.150781,0.116061,1
6,00136.jpg,1280,853,car,790,966,666,738,0.685937,0.822978,0.137500,0.084408,1
7,00145.jpg,1280,853,car,235,808,311,590,0.407422,0.528136,0.447656,0.327081,1
8,00145.jpg,1280,853,car,749,1280,335,570,0.792578,0.530481,0.414844,0.275498,1
9,00215.jpg,1280,853,car,1,1126,166,618,0.440234,0.459555,0.878906,0.529894,1
10,00490.jpg,1280,848,car,143,1166,283,574,0.511328,0.505307,0.799219,0.343160,1

In [24]:
test_df.head(10)

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
1,00249.jpg,1280,853,car,630,1221,317,579,0.723047,0.525205,0.461719,0.307151,1
19,00328.jpg,1280,960,car,80,689,376,746,0.300391,0.584375,0.475781,0.385417,1
30,00533.jpg,500,312,car,42,483,68,261,0.525000,0.527244,0.882000,0.618590,1
31,00272.jpg,1280,960,car,363,534,544,617,0.350391,0.604688,0.133594,0.076042,1
32,00272.jpg,1280,960,car,460,640,673,751,0.429688,0.741667,0.140625,0.081250,1
33,00272.jpg,1280,960,car,480,665,439,517,0.447266,0.497917,0.144531,0.081250,1
34,00272.jpg,1280,960,car,870,1043,618,689,0.747266,0.680729,0.135156,0.073958,1
35,00272.jpg,1280,960,car,702,878,343,417,0.617188,0.395833,0.137500,0.077083,1
36,00272.jpg,1280,960,car,667,852,528,607,0.593359,0.591146,0.144531,0.082292,1
37,00272.jpg,1280,960,car,940,1121,415,488,0.805078,0.470313,0.141406,0.076042,1

In [28]:
# Create train and test folder
import os
from shutil import move

train_folder = 'Dataset/train'
test_folder = 'Dataset/test'

os.makedirs(train_folder, exist_ok=True)
os.makedirs(test_folder, exist_ok=True)

In [29]:
cols = ['filename','id','center_x','center_y','w','h']
groupby_obj_train = train_df[cols].groupby('filename')
groupby_obj_test = test_df[cols].groupby('filename')

In [39]:
# Save images and labels in respective train and test folder in text format
def save_data(filename,folder_path,group_obj):
    # Define source and destination paths for the image
    src = os.path.join('.',filename)
    dst = os.path.join(folder_path,filename)

    # Check if the source image file exists before moving
    if os.path.exists(src):
        move(src,dst)

        # Save the labels if the image was successfully moved
        text_filename = os.path.join(folder_path,
                                     os.path.splitext(filename)[0]+'.txt')
        group_obj.get_group(filename).set_index('filename').to_csv(text_filename,sep=' ',index=False,header=False)
    else:
        print(f"Warning: Image file not found for {filename}. Skipping this entry.")

In [40]:
filename_series = pd.Series(groupby_obj_train.groups.keys())

In [41]:
filename_series.apply(save_data,args=(train_folder,groupby_obj_train))

Warning: Image file not found for 00001.jpg. Skipping this entry.
Warning: Image file not found for 00002.jpg. Skipping this entry.
Warning: Image file not found for 00003.jpg. Skipping this entry.
Warning: Image file not found for 00004.jpg. Skipping this entry.
Warning: Image file not found for 00005.jpg. Skipping this entry.
Warning: Image file not found for 00006.jpg. Skipping this entry.
Warning: Image file not found for 00009.jpg. Skipping this entry.
Warning: Image file not found for 00014.jpg. Skipping this entry.
Warning: Image file not found for 00018.jpg. Skipping this entry.
Warning: Image file not found for 00022.jpg. Skipping this entry.
Warning: Image file not found for 00037.jpg. Skipping this entry.
Warning: Image file not found for 00044.jpg. Skipping this entry.
Warning: Image file not found for 00048.jpg. Skipping this entry.
Warning: Image file not found for 00053.jpg. Skipping this entry.
Warning: Image file not found for 00057.jpg. Skipping this entry.
Warning: Image file not found for 00069.jpg. Skipping this entry.
Warning: Image file not found for 00074.jpg. Skipping this entry.
Warning: Image file not found for 00077.jpg. Skipping this entry.
Warning: Image file not found for 00082.jpg. Skipping this entry.
Warning: Image file not found for 00094.jpg. Skipping this entry.
Warning: Image file not found for 00095.jpg. Skipping this entry.
Warning: Image file not found for 00101.jpg. Skipping this entry.
Warning: Image file not found for 00105.jpg. Skipping this entry.
Warning: Image file not found for 00121.jpg. Skipping this entry.
Warning: Image file not found for 00124.jpg. Skipping this entry.
Warning: Image file not found for 00126.jpg. Skipping this entry.
Warning: Image file not found for 00128.jpg. Skipping this entry.
Warning: Image file not found for 00131.jpg. Skipping this entry.
Warning: Image file not found for 00136.jpg. Skipping this entry.
Warning: Image file not found for 00138.jpg. Skipping this entry.
Warning: Image file not found for 00140.jpg. Skipping this entry.
Warning: Image file not found for 00143.jpg. Skipping this entry.
Warning: Image file not found for 00144.jpg. Skipping this entry.
Warning: Image file not found for 00149.jpg. Skipping this entry.
Warning: Image file not found for 00157.jpg. Skipping this entry.
Warning: Image file not found for 00166.jpg. Skipping this entry.
Warning: Image file not found for 00184.jpg. Skipping this entry.
Warning: Image file not found for 00187.jpg. Skipping this entry.
Warning: Image file not found for 00194.jpg. Skipping this entry.
Warning: Image file not found for 00198.jpg. Skipping this entry.
Warning: Image file not found for 00204.jpg. Skipping this entry.
Warning: Image file not found for 00207.jpg. Skipping this entry.
Warning: Image file not found for 00210.jpg. Skipping this entry.
Warning: Image file not found for 00235.jpg. Skipping this entry.
Warning: Image file not found for 00237.jpg. Skipping this entry.
Warning: Image file not found for 00240.jpg. Skipping this entry.
Warning: Image file not found for 00257.jpg. Skipping this entry.
Warning: Image file not found for 00261.jpg. Skipping this entry.
Warning: Image file not found for 00266.jpg. Skipping this entry.
Warning: Image file not found for 00267.jpg. Skipping this entry.
Warning: Image file not found for 00270.jpg. Skipping this entry.
Warning: Image file not found for 00274.jpg. Skipping this entry.
Warning: Image file not found for 00277.jpg. Skipping this entry.
Warning: Image file not found for 00298.jpg. Skipping this entry.
Warning: Image file not found for 00299.jpg. Skipping this entry.
Warning: Image file not found for 00311.jpg. Skipping this entry.
Warning: Image file not found for 00316.jpg. Skipping this entry.
Warning: Image file not found for 00318.jpg. Skipping this entry.
Warning: Image file not found for 00329.jpg. Skipping this entry.
Warning: Image file not found for 00337.jpg. Skipping this entry.
Warning: Image file not found for 00340.jpg. Skipping this entry.
Warning: Image file not found for 00356.jpg. Skipping this entry.
Warning: Image file not found for 00361.jpg. Skipping this entry.
Warning: Image file not found for 00371.jpg. Skipping this entry.
Warning: Image file not found for 00373.jpg. Skipping this entry.
Warning: Image file not found for 00375.jpg. Skipping this entry.
Warning: Image file not found for 00378.jpg. Skipping this entry.
Warning: Image file not found for 00379.jpg. Skipping this entry.
Warning: Image file not found for 00381.jpg. Skipping this entry.
Warning: Image file not found for 00393.jpg. Skipping this entry.
Warning: Image file not found for 00399.jpg. Skipping this entry.
Warning: Image file not found for 00407.jpg. Skipping this entry.
Warning: Image file not found for 00408.jpg. Skipping this entry.
Warning: Image file not found for 00417.jpg. Skipping this entry.
Warning: Image file not found for 00423.jpg. Skipping this entry.
Warning: Image file not found for 00424.jpg. Skipping this entry.
Warning: Image file not found for 00429.jpg. Skipping this entry.
Warning: Image file not found for 00433.jpg. Skipping this entry.
Warning: Image file not found for 00446.jpg. Skipping this entry.
Warning: Image file not found for 00455.jpg. Skipping this entry.
Warning: Image file not found for 00457.jpg. Skipping this entry.
Warning: Image file not found for 00458.jpg. Skipping this entry.
Warning: Image file not found for 00460.jpg. Skipping this entry.
Warning: Image file not found for 00472.jpg. Skipping this entry.
Warning: Image file not found for 00475.jpg. Skipping this entry.
Warning: Image file not found for 00477.jpg. Skipping this entry.
Warning: Image file not found for 00487.jpg. Skipping this entry.
Warning: Image file not found for 00494.jpg. Skipping this entry.
Warning: Image file not found for 00506.jpg. Skipping this entry.
Warning: Image file not found for 00536.jpg. Skipping this entry.
Warning: Image file not found for 00599.jpg. Skipping this entry.
Warning: Image file not found for 0436.jpg. Skipping this entry.

0      None
1      None
2      None
3      None
4      None
       ...
412    None
413    None
414    None
415    None
416    None
Length: 417, dtype: object

In [42]:
filename_series_test = pd.Series(groupby_obj_test.groups.keys())
filename_series_test.apply(save_data,args=(test_folder,groupby_obj_test))

Warning: Image file not found for 00029.jpg. Skipping this entry.
Warning: Image file not found for 00109.jpg. Skipping this entry.
Warning: Image file not found for 00183.jpg. Skipping this entry.
Warning: Image file not found for 00191.jpg. Skipping this entry.
Warning: Image file not found for 00221.jpg. Skipping this entry.
Warning: Image file not found for 00234.jpg. Skipping this entry.
Warning: Image file not found for 00252.jpg. Skipping this entry.
Warning: Image file not found for 00262.jpg. Skipping this entry.
Warning: Image file not found for 00283.jpg. Skipping this entry.
Warning: Image file not found for 00334.jpg. Skipping this entry.
Warning: Image file not found for 00355.jpg. Skipping this entry.
Warning: Image file not found for 00364.jpg. Skipping this entry.
Warning: Image file not found for 00367.jpg. Skipping this entry.
Warning: Image file not found for 00391.jpg. Skipping this entry.
Warning: Image file not found for 00396.jpg. Skipping this entry.
Warning: Image file not found for 00484.jpg. Skipping this entry.
Warning: Image file not found for 00545.jpg. Skipping this entry.

0      None
1      None
2      None
3      None
4      None
       ...
99     None
100    None
101    None
102    None
103    None
Length: 104, dtype: object